version: "2"
services:
  server:
    build: ./server
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: npm start
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  client:
    build: ./client
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    command: npm start